sonar.organization=arrase
sonar.projectKey=arrase_atomic-explorer
sonar.sources=src,crates/atomic-math/src
sonar.tests=crates/atomic-math/tests
sonar.rust.lcov.reportPaths=lcov.info
sonar.cpd.exclusions=src/i18n/**
sonar.coverage.exclusions=src/**
